title: LinkedIn Automation Testing
email: your-email@example.com
description: >- # this means to ignore newlines until "social"
  A portfolio site for the LinkedIn Automation Testing project.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
theme: jekyll-theme-cayman
# Remove the line above and choose any supported GitHub Pages theme, such as 
# jekyll-theme-minimal, jekyll-theme-midnight, etc.

# Defaults
# Add any custom collections or defaults here
